### ISSUE TITLE
Out of Memomy

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#103]
Last fix works for convert memory leak, but next memory problem with compile cpp.

https://msdn.microsoft.com/en-us/library/c9e6fs6b.aspx
https://msdn.microsoft.com/en-us/library/ft39hh4x.aspx

> Member initializers in a constructor definition [C++ standard: 6144] (Visual C++ compiler: at least 6144).

I'am confused now, and no have idea for fix it.

**Comment by soywiz** [comment]
Ok. I'm going to try to do a proper fix. The problem is still in the reflection classes right? I can try to split it in several methods or even classes.
In the worst case it still doesnt work we can try other options:
- use gcc instead microsoft compiler for compiling
- llvm/clang
- use D (i will have to provide wrappers for it)
In this case you need a native executable for windows right?

**Comment by SergeyLabutin** [comment]
Yes, this problem with reflection.

**Comment by soywiz** [comment]
Ok. I will be able to invest 3 hours per day to this until this is fixed.

As far as I remember haxe had problems with c++ generating if/else chains that counted as high cyclomatic complexity. If that's the problem, one possible solution would be convert that into a if-else tree.

```
if (value < totalElements / 2) {
   if (value < totalElements / 4) {
      // First quarter
   } else {
      // Second quarter
   }
} else {
   // Thirth + Fourth quarter
   ...
}
```

That would be able to handle 1024 elements with just 10 levels of nesting and 1M in 20 levels (else if acts as a nested statement for microsoft c++ compiler as far as i remember) and this option doesn't use "else if" chains.

But first I have to validate that that is the problem and not the size of the method itself. We could also solve that just by that same strategy, moving some of branches to other smaller methods as required.

**Comment by SergeyLabutin** [comment]
testBigSwitchIssue103	5.313s	passed

**Comment by SergeyLabutin** [comment]
fix verified
