### ISSUE TITLE
How i can mark classes for reflection use only?

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#114]
My code may dynamic creation from files. Jtransc cut all classes without link in code. Can use any annotations for not cut custom class for my project?

**Comment by soywiz** [comment]
It discover classes as they are used. Also add classes when referenced by the ServiceLoader. i don't remember if there is an annotation called JtranscKeepExternal? If not, I can add that feature so you can use it.

**Comment by SergeyLabutin** [comment]
I not see in code, please add, this good for external libraries! Tnx.

**Comment by soywiz** [comment]
Sure

**Comment by soywiz** [comment]
I'm workong on this already.

**Comment by soywiz** [comment]
And BTW in the meantime you can create something like:

```
public class ReferenceClass {
    static public void main(String[] args) {
        ClassRequired.class;
        OtherClassRequired.class;
        OriginalClass.main(args);
    }
}
```

This class can be generated if required

**Comment by SergeyLabutin** [comment]
Tnx, i make other structure with Keep class but not create in runtime. It works good =)

**Comment by SergeyLabutin** [comment]
I close it. This good way, working fine long time =)
