### ISSUE TITLE
How sign iOS build

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#117]
I get always error
`Signing for "SpineSimpleTest1" requires a development team. Select a development team in the project editor.`

I open XCode choose company and run from XCode, and all good. But from gradle can not build. Maybe problem in few company in my account, but different projects i make for different company.

How i can sign, maybe from gradle settings?

**Comment by soywiz** [comment]
If you are using gdx-backend-jtransc:

Check this:
https://github.com/jtransc/gdx-backend-jtransc/blob/master/gdx-backend-jtransc/resources/limebuild.cmd

https://github.com/jtransc/gdx-backend-jtransc/blob/master/gdx-backend-jtransc/src/com/jtransc/media/limelibgdx/LimeApplication.java#L45

**Comment by SergeyLabutin** [comment]
Add settings in backend for provide team-id https://github.com/jtransc/gdx-backend-jtransc/pull/61/commits/282f5d19c85517831830259eb6d49a168edebb6a
