### ISSUE TITLE
C++ Windows - Too Many Heap Sections

### ISSUE THREAD

**Issue by soywiz** [jtransc/jtransc#123]
![too_many_heap_sections](https://cloud.githubusercontent.com/assets/570848/26084384/e6ab7fa4-39db-11e7-939b-d9b3e8b8aec1.png)

**Comment by soywiz** [comment]
Checking process manager:

![program_1gb](https://cloud.githubusercontent.com/assets/570848/26097884/53bbe5f8-3a26-11e7-8a7d-30fd7aeae0c8.png)

It seems that it reaches 1gb in a 32-bit process and probably that's why it is exiting with a fatal. So it seems that GC is not working or not working properly.

**Comment by intrigus** [comment]
Try compiling with ‑DLARGE_CONFIG

**Comment by intrigus** [comment]
Or it's not working properly, could also be the case. As I said: Will look into it later :)

**Comment by soywiz** [comment]
Sure. Don't worry. I'm just writting here my findings.

In this case, the benchmark creates tons of objects, without actually storing them. So the pointer is replaced in each iteration, and should be disposed. If not immediately, at least before exhausting memory with the GC.

```
benchmark("Create Instances2", new Task() {
	@Override
	public int run() {
		int out = 0;
		String s = "test";
		for (int n = 0; n < 100000; n++) {
			MyClass myClass = new MyClass(s);
			out += myClass.b;
		}
		return out;
	}
});
```

**Comment by soywiz** [comment]
Fixed: https://github.com/jtransc/jtransc/commit/5cc2a9af1c937b2ff5796948177140a3d2eff583
Also now runs faster :)

**Comment by intrigus** [comment]
Great that you fixed i!
