### ISSUE TITLE
Check cast instruction is missing/removed?

### ISSUE THREAD

**Issue by intrigus** [jtransc/jtransc#127]
I have this code:
````
public Main() {
       Object test = "hello";
	Integer t = (Integer) test;
    }
````
This obviously should result in a ClassCastException, but it doesn't.
Please have a look at https://javap.yawk.at/#g5FFiU
In line 19 is the instruction `checkcast` which verifies that a certain cast is safe to do.

When compiling to cpp there is no check cast instruction or anything similar.

**Comment by soywiz** [comment]
I'll check ASAP. And it should be tested as well.

**Comment by soywiz** [comment]
Depends on #127
