### ISSUE TITLE
StringBuffer problem

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#138]
I can not make test, it i my project for HaxeCpp target
```
  char[] test = {0x0054, 0x0065, 0x0073, 0x0074 , 0x0020, 0x00A0, 0x00A1, 0x00A2, 0x00A3, 0x00A4, 0x00A5, 0x00A6, 0x00A7, 0x00A8, 0x00A9, 0x00AA, 0x00C0, 0x00C1, 0x00C2, 0x00C3,};
  String testStr = new String(test);
  System.out.println(testStr);
  StringBuilder sb = new StringBuilder();
  for (char c : test) {
   sb.append(c);
  }
  testStr = sb.toString();
  System.out.println(testStr);
```
java output
```
Test  ???¤?¦§?©?????
Test  ???¤?¦§?©?????
```
our output
```
Test  ???¤?¦§?©?????
Test ???????????????
```
P.S. i can try make test for jtransc, but need time for it.

**Comment by soywiz** [comment]
It works on Haxe-JS but fails on Haxe-CPP:

This is the StringBuf implementation that JTransc uses on Haxe target which probably has the bug:
https://github.com/HaxeFoundation/haxe/blob/394599d7ee9e5490e8a51b18a17040a55808795f/std/cpp/_std/StringBuf.hx

**Comment by soywiz** [comment]
After investigating a bit more, the problem seems to be with String.fromCharCode:. So I'm going to replace it

https://github.com/HaxeFoundation/haxe/issues/2382
https://github.com/HaxeFoundation/haxe/issues/3072
https://github.com/HaxeFlixel/flixel/issues/1409

**Comment by SergeyLabutin** [comment]
This not fix problem, reopen please, i provide fix after previous MR accept/decline.
