### ISSUE TITLE
Closure optimizer keywords

### ISSUE THREAD

**Issue by marciodel** [jtransc/jtransc#141]
I've just tried to use Google Closure compiler and it reduced and obfuscated a sample application by an order of ~40%.

Closure added some new keywords for the typing information and it complained about the below function, because float is a reserved word:
```
N.lnewFloat = function(float) { return Int64.ofFloat(float); };
```

Please, could you change the parameter name in the next releases?

Thanks!

**Comment by soywiz** [comment]
Sure. You can use `minimizeNames=false` for reduce output further (even when closure compiler) in the case you are not using it already.
