### ISSUE TITLE
oom #119 return for JT 0.6.1

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#149]
After merge https://github.com/SergeyLabutin/jtransc/commit/bba380444f3ea55156e49a3fc1364705c7d6deb3 problem return. Last time i seen on 0.5.16 only. I try `git reset --hard HEAD~1` and no any problem with memory. I think, in this merge only one change can made it https://github.com/jtransc/jtransc/commit/511ab315e6c94bb79c97e5dcc912a2334ad9f693

**Comment by soywiz** [comment]
Shouldn't affect you since it is just for plain cpp target, not related to haxe at all.

**Comment by SergeyLabutin** [comment]
Yes, but strong working w/o and oom after update. I try find more information. Try review all my environment.

**Comment by SergeyLabutin** [comment]
i close it, if i can find more information, then reopen it.
For fix i delete this line `customTarget("windows", "haxe:windows", "exe")` but it strange because use debugHaxeCpp only and not runWindows... Looks as not dependency with plainCpp and haxeCpp, all it very strange. I not updated anything in my env today.
