### ISSUE TITLE
Is C# compiler changable?

### ISSUE THREAD

**Issue by fxzjshm** [jtransc/jtransc#156]
I want to use mono on Windows, because my csc compiler isn't working.
It said:
```
Execute command C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319\csc /debug:full /unsafe+ /checked- /optimize+ /define:UNSAFE /nowarn:169 D:\workspace\Polyfiter\jtransc\build\jtransc-cs\program.cs
Microsoft (R) Visual C# Compiler version 4.6.1586.0
                                                    for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

program.cs(137329,20): error CS0266: ??????????JA_0???????????JA_L?????????????????(?????????????)
program.cs(341415,8): error CS0103: ??????????в??????????pc??
program.cs(341757,37): error CS0031: ???????1???????????bool??
program.cs(341758,38): error CS0031: ???????0???????????bool??
```
But I cannot find some ways to change it. It appeared even after I installed VS2017, probably because jtransc didn't know the new compiler. 
Could you please add some options to customize the compiler?
Thank you.

**Comment by fxzjshm** [comment]
Or you may call a compiler in PATH, because I can call the correct csc directly using command "csc".

**Comment by soywiz** [comment]
I can try to detect `csc` in path and use it when available with a fallback to csc or mono's one. But I think it would be good to be able to select the compiler somehow. Maybe with something in the `jtransc {}` gradle block.
So I'm going to do both.
