### ISSUE TITLE
Stress test

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#168]
I write stress test https://github.com/jtransc/jtransc-examples/pull/14 for #165, but find new bug with haxe.
Execute command C:\tools\HaxeToolkit\haxe\haxelib run lime test cpp -debug -Dsource-header=0
```
src/z/TZC.hx:10: lines 10-15 : A class constructor can't have a return value
                                                                             src/z/DC.hx:24: characters 31-33 : Module z.STD is loaded with a different case than z.Std
src/z/VE.hx:2980: characters 25-42 : Binding new is only allowed on class types
src/z/VE.hx:2980: characters 25-42 : For function argument 'value'
src/z/O.hx:12698: characters 2-23 : Binding new is only allowed on class types
```
Reproduced on both os: windows and mac

**Comment by SergeyLabutin** [comment]
If remove in test
```
		ddd.method4();
		ddd.method5();
		ddd.method6();
```
then error: `rc/z/ZWD.hx:7: characters 12-15 : Unexpected new`

**Comment by soywiz** [comment]
Check again. This should be fixes already. That was related to a three-letter keyword that was used when generating minimized names

**Comment by soywiz** [comment]
Also I have done some work to reduce complexity of some generated big methods. Which may be enough for your huge case. If it is not, please tell me and I will try to improve it further.
