### ISSUE TITLE
New classes introduces by ProgramFeatures are processed by Plugins 

### ISSUE THREAD

**Issue by marciodel** [jtransc/jtransc#171]
Since the ProgramFeatures run after the treeshaking there is no way to process them in a plugin. E.g., new classes introduced by LambdaProgramFeature are not processed by plugins.

**Comment by soywiz** [comment]
One possible solution could be add another hook for plugins to execute after program features.
Do you have any other suggestion there?

**Comment by marciodel** [comment]
No. I think this solution is good.
