### ISSUE TITLE
Mac clang use one thread only

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#173]
On mac compiling is very long, on windows this phase 4x-6x faster.

**Comment by soywiz** [comment]
Relevant info: https://blog.kitware.com/cmake-building-with-all-your-cores/

Though in haxe i think they handle by themselves this. So I think this should be a bugreport for lime or haxe. Unless there is a flag we can add to handle this

**Comment by SergeyLabutin** [comment]
ok

**Comment by soywiz** [comment]
If you find and haxe or lime flag to tell clang to parallelize this. Feel free to reopen this or to add a PR.
