### ISSUE TITLE
Memory functions

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#204]
Always return 8G for Haxecpp target (tested on windows)

https://github.com/jtransc/gdx-backend-jtransc/pull/72
```
 @JTranscMethodBody(target = "cpp", value = "return GC_get_free_bytes();")
 @JTranscMethodBody(target = "php", value = "return N::d2j((float)0.0);")
 public long freeMemory() {
 return 8 * 1024 * 1024 * 1024L;
 }
```

Maybe it's not a bug, but need more tests, i will check it today.

**Comment by soywiz** [comment]
For what i have seen it requires `@HaxeMethodBody` annotations. Just implemented for jtransc direct targets

**Comment by SergeyLabutin** [comment]
Confirmed broken for Haxe. Haxe have not this functions only use and allocated on this time memory, not free. I can try change backend for haxe use one template and other targets use other template with JT use.

**Comment by soywiz** [comment]
Not sure if haxe provides exact match for these functions. But the portable way of doing so it works on java too is this i think. We can also expose thibgs like this is JTranscSystem class
