### ISSUE TITLE
Integrate with codecov.io

### ISSUE THREAD

**Issue by soywiz** [jtransc/jtransc#233]
https://codecov.io

**Comment by intrigus** [comment]
What's this for?

**Comment by soywiz** [comment]
Code coverage. We can detect code that is not being tested (no referenced in tests any potentially not working or with bugs)

**Comment by SergeyLabutin** [comment]
I use jacoco, this good idea use code coverage. But don't use codecov, is it wrapper for jacoco?

**Comment by soywiz** [comment]
As far as I understand (not tested yet) it is a bot that shows the coverage reports directly in github: https://d234q63orb21db.cloudfront.net/685e381330164f79197bc0e7f75035c6f1b9d7d0/media/images/home/comment.png

**Comment by soywiz** [comment]
But jacoco is breaking our integration tests right now because it add some fields. So I'm trying to disable jacoco bytecode manipulation to our class files so tests passes. Once tests passes, it will upload reports and we will be able to see codecov it in action (hopefully)

**Comment by soywiz** [comment]
Example: https://github.com/codecov/pathmap/pull/9#issuecomment-318760182
