### ISSUE TITLE
Support synchronized methods in Haxe

### ISSUE THREAD

**Issue by soywiz** [jtransc/jtransc#242]
Following fxzjshm work here: https://github.com/jtransc/jtransc/pull/210

We should implement synchronized methods in Haxe. Probably the best way would be to create two functions. One public with the same signature, and other private and without reflection with the actual body, the public version should call private version doing `try + catch` emulating finally. Private function should have access to `super` keyword when available.

The other option would be intercept returns inside synchronized bodies doing the mutex release before returning and catching a exception with rethrowing at the function level . That should work too (hopefully).

**Comment by SergeyLabutin** [comment]
For support network in haxe for me need this construction
```
private Object lockObject = new Object();
void request() {
  synchronized(lockObject ) {
  }
}
```

**Comment by soywiz** [comment]
I thought that synchronized blocks were already implemented in haxe and the only missing thing was synchronized methods.
It should be easy to implement synchronized blocks. But i wont be able to write any code until a couple of days (i just have my mobile phone).

**Comment by SergeyLabutin** [comment]
Seems as not working synchronized blocks
`{{ HAXE_METHOD_ANNOTATIONS }} static public inline function c<T, S> (value:T, c:Class<S>):S return cast value;`
i do not understand how it work as sync =) i will wait you for help me =)) i think this will be hard for me =(

**Comment by soywiz** [comment]
I have seen the code. Haxe target doesnt seem ti implement neither sync methods nor sync blocks. I will implement sync blocks first, and then sync methods. I will work on that maybe tomorrow or the day after tomorrow when i finally get home
