### ISSUE TITLE
Missing classes for pure libgdx

### ISSUE THREAD

**Issue by intrigus** [jtransc/jtransc#246]
Missing classes:
* java.net.ServerSocket
* javax.sound.*
* java.nio.channels.SocketChannel
* java.util.Optional

**Comment by soywiz** [comment]
Going to work on Socket + Optional.
Later will work on sound. Maybe we can use a service implemented as dummy here, and then implement properly at libgdx level.

**Comment by soywiz** [comment]
Should be done in #248 and #259. ServerSocket is implemented as dummy. The same goes for sound stuff. After you verify that you don't require anymore classes, and send me a link where sound API is used, I will try to implement it so it doesn't fail but doesn't ouput anything either and that will allow to be implemented from the outside (maybe including a library for providing it) as a service.

**Comment by intrigus** [comment]
* java.nio.file.*
