### ISSUE TITLE
Typo in link in repo description

### ISSUE THREAD

**Issue by dimon222** [jtransc/jtransc#279]
This might sounds weird, but the link is missing "c" in domain.
jtransc.om-> jtransc.com

![image](https://user-images.githubusercontent.com/2671025/31921153-bbfe6a62-b83b-11e7-9ab2-1304d80c2c9b.png)

**Comment by soywiz** [comment]
Right! Fixed.

The other thing that was wrong was https.
Since I'm using github pages it is not supported. I'm creating a separate issue for that.
But we are in 2017, so I'm definitely going to put https.

https issue -> #280

Thanks for reporting
