### ISSUE TITLE
Could not find com.jtransc:jtransc-main:unspecified

### ISSUE THREAD

**Issue by SOF3** [jtransc/jtransc#297]
I am using Gradle. I added `classpath("com.jtransc:jtransc-gradle-plugin:0.2.5")` into `buildscript.dependencies` and `id("com.jtransc") version "0.6.8"` into `plugins`, and I get these errors:

- Could not find com.jtransc:jtransc-main:unspecified
- Could not find com.jtransc:jtransc-gradle-plugin:0.2.5

I already have mavenCentral() and jcenter() in my repositories. Did I miss something?

**Comment by SOF3** [comment]
Never mind, I structured my build.gradle.kts wrongly.

**Comment by Vojtasii** [comment]
Hello, do you remember what you have structured wrongly in your build.gradle.kts file? I am only getting the first error

- Could not find com.jtransc:jtransc-main:unspecified

**Comment by SOF3** [comment]
nope, I don't even remember what I was developing back then.

**Comment by Vojtasii** [comment]
Ok, thanks for responding :)
