### ISSUE TITLE
Where are the class files parsed and where is Haxe generated?

### ISSUE THREAD

**Issue by intrigus** [jtransc/jtransc#39]
Hi, I'd look to know where .class files are parsed.
The haxe code seems to be generated [here](https://github.com/jtransc/jtransc/blob/master/jtransc-gen-haxe/src/com/jtransc/gen/haxe/haxe_gen.kt), is this right?

I'd like to have a look at it and maybe find some optimizations :)

**Comment by soywiz** [comment]
Sure `haxe_gen.kt` is the one that converts the AST into actual code.

Generated code is output here:
https://github.com/jtransc/jtransc/blob/master/jtransc-gen-haxe/src/com/jtransc/gen/haxe/haxe.kt#L110

On tests it uses OS tempfolder as far as I know. On normal builds, it uses `target` or `build` folder from maven and gradle respectively. Inside that there should be a jtransc-haxe/src with `.hx` and `.hx.map` files per class.

Class files are visited here generating the AST:
https://github.com/jtransc/jtransc/blob/master/jtransc-core/src/com/jtransc/types/asm_ast.kt

It tries to reconstruct expressions as possible.

Optimization stuff here (it include some commits):
https://github.com/jtransc/jtransc/issues/9

AST Optimizer:
https://github.com/jtransc/jtransc/blob/master/jtransc-core/src/com/jtransc/ast/optimize/ast_optimize.kt

"Relooper":
https://github.com/jtransc/jtransc/blob/master/jtransc-core/src/com/jtransc/graph/Relooper.kt
Currently it just optimize functions without loops: Just if/else chains and it generate big code on some cases with && and || that I didn't looked at yet.

I'm not working on optimizations right now, so if you are going to look at it, cool :)

**Comment by soywiz** [comment]
Since this was just a question, I'm closing it.
