### ISSUE TITLE
Remove squareup.okhttp

### ISSUE THREAD

**Issue by intrigus** [jtransc/jtransc#44]
I don't think [this](https://github.com/jtransc/jtransc/commit/522f541fd7c53ea181d61ae52851c67b32308772#diff-caa9ecc957bf91f4b88e919555b89e68) is really needed.
It should be removed, shouldn't it?

**Comment by soywiz** [comment]
Just copied it from RoboVM RT. I'm not using that RT "yet". Probably I will end just copy the stuff I need to jtransc-rt. It has tons of dependencies and too complex stuff that can be simplified.
I didn't notice that okhttp was not being used. If that's the case, could you do a PR removing it? As long as travis says it is ok, it's fine.

**Comment by intrigus** [comment]
I didn't check whether okhttp was being used, but I see no reason, why it should be included in a runtime.

**Comment by soywiz** [comment]
It is not included if not referenced. JTransc starts from your main and generate a working set based on the used and/or referenced classes, not just the whole runtime. Though right now it include all the methods/fields even when they are not used.

Right now JTransc first tries to locate the referenced class in:
* jtransc-rt
* jtransc-rt-full
* jtransc-rt-core

If not found it will check in your code. So right now almost all RT classes will be used from plain JTransc -rt which do not reference okhttp at all so it won't get to the output.

**Comment by soywiz** [comment]
I removed some days ago jtransc-rt-full, I forked robovm as RT reference.
