### ISSUE TITLE
Move to gradle

### ISSUE THREAD

**Issue by soywiz** [jtransc/jtransc#56]
In order to use incremental compilation with kotlin, we should try to switch from maven to gradle in the JTransc repository.

**Comment by vicboma1** [comment]
🤘🤘🤘

**Comment by soywiz** [comment]
Ok. So this was a bit complex. Now I understand a bit more gradle. Troubles I had, and leasons learned:

* Since I have a custom RT, I needed to say that tests depended on RT, but not to include them in the classpath: `project(':jtransc-main').compileKotlin.dependsOn(project(':jtransc-rt').test)`
* Gradle keeps classes and resources in two different folders
* Gradle cache has a hash in its path that I don't know how to calculate :)
* Compile encoding is not UTF-8 by default
* Gradle is cool for some stuff, and a bit messy for others
* But the overall is better I think:
   * Deployment is now faster and simplified.
   * Now compilation can be incremental with `kotlin.incremental=true` in gradle.properties
