### ISSUE TITLE
Present your work at WWX?

### ISSUE THREAD

**Issue by elsassph** [jtransc/jtransc#7]
https://github.com/silexlabs/wwx2016/issues

**Comment by soywiz** [comment]
That could be interesting! Thanks for reporting. It should have matured by then.
The event is 2016-05-27 until 2016-05-30 @ Paris right?
Which is the due date for applying? I have to be sure whether I would be able to assist.

**Comment by elsassph** [comment]
You should still create an issue to see if there is interest but warm that you can't engage yourself for now.

**Comment by soywiz** [comment]
https://github.com/silexlabs/wwx2016/issues/15
