### ISSUE TITLE
D or Go targets

### ISSUE THREAD

**Issue by soywiz** [jtransc/jtransc#70]
Now it is super easy to add new targets. Since now it is just output specific syntax, and lot of runtime specific stuff has gone with metaprogramming.

It seems that D has evolved a lot since last time I used it. And there are several compilers for it: DMD, GDC and LDC and lots of platforms using it. Even AAA game QuantumBreak seems to use it. http://dconf.org/2016/talks/watson.html

D supports GC directly integrated in the language and even when supporting even inline asm, it is higher level than C++, so output should be easier. This language also supports GOTO: https://dlang.org/spec/statement.html#GotoStatement

---

Go could be another option but differs more from JVM OOP so it should be harder to create a target.

**Comment by intrigus** [comment]
I'd suggest stabilizing the targets and implementing the java memory model for the cpp target.

**Comment by soywiz** [comment]
JS target seems to be fully working already.
I do not have too much experience with C++ to implement a GC on it (though I could check RoboVM for that) and I'm having problems running it on windows with lastest visual studio version.
And D seems to be portable enough, it seems to work on Android and iOS too. http://wiki.dlang.org/LDC#Project_status

But at any rate, I could add new targets later and stabilize again Haxe target first.

**Comment by soywiz** [comment]
Experimental D target is already mostly implemented.
* There are minor differences when converting double to String.
* String Literals are still recreated each time (will fix in following commits).
* RegExp has issues
* Process stuff not implemented yet
The rest seems to work just OK.
I will improve in following versions.

Added a new target allowed to refactor common generation code.

Regarding to D api the std seems to have everything needed for the java's std.
Performance looks promising. Even when much slower than JS (except for loops and arithmetic), it is due to unnecessary casting everywhere. In following versions prior to 1.0, I will implement SSA form + remove intermediate casting, and will improve one order of magnitude. Since D has gotos, relooper is not necessary to get great performance.
