### ISSUE TITLE
Raw LWJGL Usage

### ISSUE THREAD

**Issue by sirsavary** [jtransc/jtransc#90]
In the examples repository, there are many examples using LibGDX but I don't see any using just LWJGL, although I did see "raw LWJGL" mentioned in a post on the forums. I'm wondering if it's at all possible to use jtransc with just LWJGL.

 I noticed a "jtransc-media-lwjgl" library but unfortunately there isn't any documentation associated with it (that I saw).

**Comment by soywiz** [comment]
Here there is an unmodified example:

https://github.com/jtransc/jtransc-examples/tree/master/libgdx/cuboc

The *magic* is done inside huild.gradle script.

https://github.com/jtransc/jtransc-examples/blob/master/libgdx/cuboc/build.gradle

Check dependencies block with jtransc library dependency (that override classes) + jtransc block to define specific stuff.

**Comment by soywiz** [comment]
I'm closing this since I put an explanation as a comment.
