### ISSUE TITLE
Enum with override members

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#94]
Hi!

if in HelloWorld add next line
`TreeMap<String, String> map = new TreeMap<>();`
then you can see error
* What went wrong:
```
Execution failed for task ':debugHaxeCpp'.
> com.jtransc.error.InvalidOperationException: Can't find AstMethodRef(java.util.TreeMap$Bound$1,values,()[Ljava/util/TreeMap$Bound$1
```

In my project i have more errors with different Enums, i think it one problem, but i can not find solution.

If you can, please, help me.

**Comment by soywiz** [comment]
I'll check it out. Maybe it is related to treeshaking?

**Comment by soywiz** [comment]
Please, try to add here:
https://github.com/jtransc/jtransc/blob/master/jtransc-gradle-plugin/example/build.gradle#L62

`treeshaking = true` just like this:

https://github.com/jtransc/jtransc-examples/blob/master/hello-world/build.gradle#L11

The problem still happens?

**Comment by SergeyLabutin** [comment]
Yes.
I think we find problem, JEnumPugin generate metod values, but if this override parent Enum then can not replace. In decompile java code i see values is static method and can not be override. I try check this.

**Comment by SergeyLabutin** [comment]
For example INCLUSIVE convert to Bound$1 and try add values(), but Bound as parent have static values()
```
enum Bound {
        INCLUSIVE {
            @Override public String leftCap(Object from) {
                return "[" + from;
            }
            @Override public String rightCap(Object to) {
                return to + "]";
            }
        },
...
```

**Comment by soywiz** [comment]
Related (information for me):

https://github.com/jtransc/jtransc/blob/master/jtransc-core/src/com/jtransc/plugin/enum/EnumJTranscPlugin.kt#L13

https://github.com/jtransc/jtransc/blob/master/jtransc-rt/src/java/util/TreeMap.java#L1060
